### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by atherdon** [deanmac5/UdaciFitness#1]
Hi @deanmac5, i find this repository and decided to write you a message. My name is Arthur and I'm a founder of a small startup(Groceristar). Will you be interested to contribute to our open source projects and gain some experience in startup?
This is accounts of our organizations: [ChickenKyiv](https://github.com/ChickenKyiv) and [Groceristar](https://github.com/GroceriStar)
This is our AngelList account: https://angel.co/groceristar
This is our Medium blog: https://medium.com/groceristar

Tell me what do you think,
Arthur

**Comment by deanmac5** [comment]
Thanks Arthur it looks interesting but I've got a bunch of projects at the moment. If I get a chance I'll help out but don't count on me.
